---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: simple-gpu-test
  namespace: default
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: simple-gpu-test
    spec:
      nodeSelector:
        kubernetes.io/hostname: nvidia
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          gpus:
            - name: gpu1
              deviceName: nvidia.com/gpu
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
            cpu: "1"
          limits:
            memory: 2Gi
            cpu: "1"
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo