apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dneg-vm
  namespace: dneg
spec:
  runStrategy: Manual

  dataVolumeTemplates:
    - metadata:
        name: win10-rootdisk
      spec:
        source:
          blank: {}
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

  template:
    metadata:
      labels:
        kubevirt.io/domain: win10
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          model: host-passthrough
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
              bootOrder: 2

            - name: cdromiso
              cdrom:
                bus: sata
              bootOrder: 1

            - name: virtiodisk
              cdrom:
                bus: sata

          interfaces:
            - name: default
              masquerade: {}

          autoattachGraphicsDevice: true

      networks:
        - name: default
          pod: {}

      volumes:
        - name: rootdisk
          dataVolume:
            name: win10-rootdisk

        - name: cdromiso
          persistentVolumeClaim:
            claimName: win10-iso

        - name: virtiodisk
          containerDisk:
            image: quay.io/kubevirt/virtio-container-disk:v1.7.0
