apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: certmanager-release
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: certmanager-repo
      interval: 1h
  interval: 1m0s
  releaseName: cert-manager

  values:
    installCRDs: true