apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    speaker:
      enabled: true
      tolerations:
        - operator: Exists