apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  commonName: homepage.192-168-1-201.sslip.io
  dnsNames:
    - homepage.192-168-1-201.sslip.io