apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: letsencrypt-cert
    kind: ClusterIssuer

  dnsNames:
    - homepage.192.168.1.201.sslip.io