apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage

spec:
  entryPoints:
    - web
    - websecure

  routes:
    - match: Host(`homepage.192-168-1-201.sslip.io`) &&
             (PathPrefix(`/`) ||
              PathPrefix(`/api`) ||
              PathPrefix(`/_next`) ||
              PathPrefix(`/config`) ||
              PathPrefix(`/favicon`))
      kind: Rule
      services:
        - name: homepage
          port: 3000
  
  tls:
    secretName: homepage-tls