apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage

spec:
  entryPoints:
    - web
    - websecure

  routes:
    - match: - PathPrefix(`/homepage`) || PathPrefix(`/_next`) || PathPrefix(`/favicon`) || PathPrefix(`/site.webmanifest`)
      kind: Rule
      middlewares:
        - name: homepage-strip
      services:
        - name: homepage
          port: 3000