apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage-release
  namespace: homepage
spec:
  chart:
    spec:
      chart: homepage
      version: 2.x.x
      sourceRef:
        kind: HelmRepository
        name: homepage-repo
      interval: 1h
  interval: 1m0s
  releaseName: homepage

  values:
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
    env:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com

      services:
        - Homelab:
            - Traefik:
                icon: traefik.png
                href: http://192.168.1.201/dashboard
                description: Network controller
            
            - Grafana:
                icon: grafana.png
                href: http://192.168.1.201/grafana
                description: monitoring
            
            - Longhorn:
                icon: longhorn.png
                href: http://192.168.1.201/longhorn
                description: storage
        - widget:
            type: traefik
            url: http://192.168.1.201/dashboard

      widgets:
        - resources:
            cpu: true
            memory: true
            disk: /