apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgress_repo.yaml
  - redis_repo.yaml
  - affine-deploy.yaml
  - affine-service.yaml
  - ingress.yaml
  - postgres_deploy.yaml
  - redis_deploy.yaml
