apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgress-repo.yaml
  - redis-repo.yaml
  - affine-deploy.yaml
  - affine-service.yaml
  - ingress.yaml
