apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: affine-redis
  namespace: affine
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "18.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    auth:
      enabled: false
