apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-community
      version: 57.x.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
      interval: 1h
  interval: 1m0s
  releaseName: prometheus

  values:
    prometheus:
      prometheusSpec:
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    grafana:
      enabled: true
      adminPassword: changeme
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi
    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi