apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 57.x.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
      interval: 1h
  interval: 1m0s
  releaseName: prometheus

  values:
    prometheus:
      prometheusSpec:
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    grafana:
      enabled: true
      adminPassword: changeme
      grafana.ini:
        server:
          root_url: http://192.168.1.201/grafana
          serve_from_sub_path: true
          protocol: http

      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi
    
    nodeExporter:
      enabled: true

        
    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi